<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFrameworks>net10.0;net48</TargetFrameworks></PropertyGroup>
  <ItemGroup><ProjectReference Include="../PbiBench.Core/PbiBench.Core.csproj" /></ItemGroup>
  <ItemGroup><EmbeddedResource Include="DaxFunctions.txt" /></ItemGroup>
  <ItemGroup><None Update="TE2_GRAMMAR_LICENSE.txt" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'"><PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" /></ItemGroup>
</Project>
