<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PbiBench.CSharp.LanguageService/PbiBench.CSharp.LanguageService.csproj" />
    <ProjectReference Include="../PbiBench.Core/PbiBench.Core.csproj" />
    <ProjectReference Include="../PbiBench.Semantic/PbiBench.Semantic.csproj" />
    <ProjectReference Include="../PbiBench.Dax.LanguageService/PbiBench.Dax.LanguageService.csproj" />
    <Reference Include="TabularEditor"><HintPath>../../vendor/TabularEditor2-2.28.0/TabularEditor/bin/$(Configuration)/TabularEditor.exe</HintPath></Reference>
    <Reference Include="TOMWrapper"><HintPath>../../vendor/TabularEditor2-2.28.0/TOMWrapper/bin/$(Configuration)/TOMWrapper.dll</HintPath></Reference>
    <Reference Include="FastColoredTextBox"><HintPath>../../vendor/TabularEditor2-2.28.0/packages/FCTB.2.16.24/lib/FastColoredTextBox.dll</HintPath></Reference>
    <Reference Include="Microsoft.AnalysisServices.Tabular"><HintPath>../../vendor/TabularEditor2-2.28.0/TabularEditor/bin/$(Configuration)/Microsoft.AnalysisServices.Tabular.dll</HintPath></Reference>
    <Reference Include="Microsoft.AnalysisServices.Core"><HintPath>../../vendor/TabularEditor2-2.28.0/TabularEditor/bin/$(Configuration)/Microsoft.AnalysisServices.Core.dll</HintPath></Reference>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
